apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: java-maven
spec:
  params:
  - name: git-revision
  - name: git-commit-message
  - name: git-repo-url
  - name: git-repo-name
  - name: content-type
  - name: pusher-name
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      generateName: java-maven-
      labels:
        app.kubernetes.io/instance: ploigos-quickstart
        tekton.dev/pipeline: java-maven
      namespace: ploigos-quickstart-examples
    spec:
      params:
      - name: mvnArgs
        value:
          - "--no-transfer-progress"
          - "-DskipITs"
          - "-f"
          - "getting-started/"
          - "package"
      - name: appRepoUrl
        value: https://github.com/dwinchell/quarkus-quickstarts.git
      - name: appImage
        value: image-registry.openshift-image-registry.svc:5000/quarkus-quickstart-examples/java-maven:latest
      - name: appRepoRef
        value: main
      - name: containerBuildContext
        value: getting-started/
      - name: containerfile
        value: src/main/docker/Dockerfile.jvm
      - name: verbose
        value: 'true'
      pipelineRef:
        name: java-maven
      resources: []
      status: null
      workspaces:
      - name: home
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp2
            volumeMode: Filesystem
      - name: app
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp2
            volumeMode: Filesystem
      - emptyDir: {}
        name: maven-settings
      - emptyDir: {}
        name: container-auth
