apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01_apply_manifest_task.yaml
  - 01_binding.yaml
  - 02_template.yaml
  - 02_update_deployment_task.yaml
  - 04_event_listener.yaml
  - 04_pipeline.yaml
