apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rekor
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    chart: rekor
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: main
    helm:
      releaseName: rekor-0.2.12

  destination:
    namespace: sigstore
    server:
      ingress:
        annotations:
          route.openshift.io/termination: "edge"
        hostname: rekor.apps.cluster-pp5xc.pp5xc.sandbox173.opentlc.com

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
