apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: java-maven
  namespace: ploigos-quickstart-examples
spec:
  params:
  - name: git-revision
  - name: git-commit-message
  - name: git-repo-url
  - name: git-repo-name
  - name: content-type
  - name: pusher-name
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
      generateName: java-maven-
      labels:
        app.kubernetes.io/instance: ploigos-quickstart
        tekton.dev/pipeline: java-maven
      namespace: ploigos-quickstart-examples
    spec:
      params:
      - name: mvnArgs
        value: --no-transfer-progress -DskipITs -f getting-started/ package
      - name: verbose
        value: "true"
      - name: appRepoUrl
        value: https://github.com/quarkusio/quarkus-quickstarts.git
      - name: appRepoRef
        value: main
      - name: appImage
        value: ploigos-quickstart-examples/java-maven:latest
      - name: targetRegistry
        value: image-registry.openshift-image-registry.svc
      - name: tlsVerify
        value: "true"
      - name: containerBuildContext
        value: .getting-started/
      - name: containerfile
        value: src/main/docker/Dockerfile.jvm
      - name: workflowWorkersImagePullPolicy
        value: IfNotPresent
      pipelineRef:
        name: java-maven
      resources: []
      status: null
      workspaces:
      - name: home
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp2
            volumeMode: Filesystem
      - name: app
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: gp2
            volumeMode: Filesystem
      - emptyDir: {}
        name: maven-settings
      - emptyDir: {}
        name: container-auth
